--- 
- 
  become: true
  become_method: sudo
  hosts: all
  name: "Update the path in ansible container"
  remote_user: ec2-user
  vars: 
    ansible_ssh_private_key_file: /usr/share/ansible-dir/ansible-opsera/keys/test.pem
  roles: 
    - nginx
